payum:
  security:
    token_storage:
      App\Entity\PaymentToken: { doctrine: orm }

  storages:
    App\Entity\TeamPayment: { doctrine: orm }

  gateways:
    paypal:
      factory: 'paypal_express_checkout'
      username: '%env(PAYPAL_USERNAME)%'
      password: '%env(PAYPAL_PASSWORD)%'
      signature: '%env(PAYPAL_SIGNATURE)%'
      sandbox: '%env(bool:PAYPAL_SANDBOX)%'