payum:
  security:
    token_storage:
      App\Entity\PaymentToken: { doctrine: orm }

  storages:
    App\Entity\TeamPayment: { doctrine: orm }

  gateways:
    paypal:
      factory: 'paypal_express_checkout'
      username: 'will-facilitator_api1.arslett.uk'
      password: 'BCJB2KHLPQU2Q6N6'
      signature: 'AVdbhFjJS0JUTXX9up4BHnZd1w4KA.znvlSnSpwJJ8U0C8GKgIPPHrIP'
      sandbox: true