security:

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:

        user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true

    access_control:
         - { path: ^/profile, roles: ROLE_USER }
