security:

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:

        user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        jwt_login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               api_login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            anonymous: ~
            form_login:
                login_path: user_login
                check_path: user_login
                default_target_path: registration_root
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   user_logout
                target: user_login
            switch_user: true

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_ALLOWED_TO_SWITCH

    access_control:
        - { path: ^/registration/teams,     roles: ROLE_USER }
        - { path: ^/registration/walkers,   roles: ROLE_USER }
        - { path: ^/registration/events,    roles: ROLE_ADMIN }
        - { path: ^/api,       roles: ROLE_API_USER }
