version: '2.1'

volumes:
  mysql:
    driver: local

services:
  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 32768:3306
    healthcheck:
      test: 'mysqladmin -u root -p$MYSQL_ROOT_PASSWORD ping --silent'
      interval: 2s
      timeout: 3s
      retries: 15

  php:
    image: php:7.2-fpm-pdo-mysql
    build:
      context: docker
      dockerfile: PHPDockerfile
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env

  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./public:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    ports:
      - ${HTTP_PORT}:80