version: '2.1'

volumes:
  mysql:
    driver: local

services:

  php:
    image: php:7.2-fpm-composer-pdo-mysql-zip-xml-intl
    build:
      context: docker
      dockerfile: PHPDockerfile
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    healthcheck:
      test: 'mysql -u $MYSQL_USER -p$MYSQL_PASSWORD --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 3s
      retries: 15

  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./public:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    ports:
      - ${HTTP_PORT}:80