version: 2

jobs:
  build:
    machine: true
    steps:

      - checkout

      - run:
          name: "Code Sniffer (PSR-2 Coding Standards)"
          command: "docker-compose exec php vendor/bin/phpcs --standard=PSR2 --ignore=/Migrations/ src"

      - run:
          name: "Copy .env"
          command: "cp .env.dist .env"

      - run:
          name: "Copy JWT certificates"
          command: "cp ssl/jwt.dist/* ssl/jwt"

      - run:
          name: "Build"
          command: "bin/build"

      - run:
          name: "PHPUnit"
          command: "docker-compose exec php vendor/bin/phpunit --log-junit .circleci/test-results/phpunit/results.xml"

      - run:
          name: "Behat"
          command: "docker-compose exec php vendor/bin/behat --no-snippets --format junit --out .circleci/test-results/behat --format pretty --out std"

      - store_test_results:
          path: ".circleci/test-results"
