version: 2

jobs:
  build:
    machine: true
    steps:

      - checkout

      - run:
          name: "Copy .env"
          command: "cp .env.dist .env"

      - run:
          name: "Build"
          command: "bin/build"

      - run:
          name: "Run PHPUnit"
          command: "docker-compose exec php vendor/bin/phpunit --log-junit .circleci/test-results/phpunit/results.xml"

      - run:
          name: "Run Behat"
          command: "docker-compose exec php vendor/bin/behat --format junit --out .circleci/test-results/behat --format pretty --out std"

      - store_test_results:
          path: ".circleci/test-results"
