root:
   path: /
   controller: App\Controller\DefaultController

user_register:
    path: /user/register
    controller: App\Controller\User\UserRegisterController
    
user_login:
    path: /user/login
    controller: App\Controller\User\UserLoginController

user_logout:
    path: /user/logout

team_list:
    path: /teams/list
    controller: App\Controller\Team\TeamListController

team_create:
    path: /teams/create
    controller: App\Controller\Team\TeamCreateController

team_show:
    path: /teams/{team_id}
    controller: App\Controller\Team\TeamShowController

walker_create:
    path: /teams/{team_id}/walkers/create
    controller: App\Controller\Walker\WalkerCreateController

api_login:
    path: /api/login