root:
   path: /
   controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
   defaults:
       path: /registration/teams/list
       permanent: true

registration_root:
  path: /registration
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /registration/teams/list
    permanent: true

user_register:
    path: /registration/user/register
    controller: App\Controller\User\UserRegisterController

user_update:
    path: /registration/user/update
    controller: App\Controller\User\UserUpdateController
    
user_login:
    path: /registration/user/login
    controller: App\Controller\User\UserLoginController

user_logout:
    path: /registration/user/logout

team_root:
   path: /registration/teams
   controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
   defaults:
       path: /registration/teams/list
       permanent: true

team_list:
    path: /registration/teams/list
    controller: App\Controller\Team\TeamListController

team_create:
    path: /registration/teams/create
    controller: App\Controller\Team\TeamCreateController

team_show:
    path: /registration/teams/{team_id}
    controller: App\Controller\Team\TeamShowController

team_update:
    path: /registration/teams/{team_id}/update
    controller: App\Controller\Team\TeamUpdateController

team_drop:
    path: /registration/teams/{team_id}/drop
    controller: App\Controller\Team\TeamDropController

team_reinstate:
    path: /registration/teams/{team_id}/reinstate
    controller: App\Controller\Team\TeamReinstateController

team_payment_capture:
    path: /registration/teams/{team_id}/payments/capture
    controller: App\Controller\Team\TeamPaymentCaptureController

team_payment_verify:
    path: /registration/teams/payments/verify
    controller: App\Controller\Team\TeamPaymentVerifyController

walker_create:
    path: /registration/teams/{team_id}/walkers/create
    controller: App\Controller\Walker\WalkerCreateController

walker_update:
    path: /registration/walkers/{walker_id}/update
    controller: App\Controller\Walker\WalkerUpdateController

walker_delete:
    path: /registration/walkers/{walker_id}/delete
    controller: App\Controller\Walker\WalkerDeleteController

event_root:
    path: /registration/events
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
       path: /registration/events/list
       permanent: true

event_list:
    path: /registration/events/list
    controller: App\Controller\Event\EventListController

event_create:
    path: /registration/events/create
    controller: App\Controller\Event\EventCreateController

event_show:
    path: /registration/events/{event_id}/show
    controller: App\Controller\Event\EventShowController

event_update:
    path: /registration/events/{event_id}/update
    controller: App\Controller\Event\EventUpdateController

event_duplicate:
    path: /registration/events/{event_id}/duplicate
    controller: App\Controller\Event\EventDuplicateController

event_delete:
    path: /registration/events/{event_id}/delete
    controller: App\Controller\Event\EventDeleteController
    
hike_create:
    path: /registration/events/{event_id}/hikes/create
    controller: App\Controller\Hike\HikeCreateController

hike_update:
    path: /registration/hikes/{hike_id}/update
    controller: App\Controller\Hike\HikeUpdateController

hike_delete:
    path: /registration/hikes/{hike_id}/delete
    controller: App\Controller\Hike\HikeDeleteController

api_login:
    path: /api/login

payum_all:
  resource: "@PayumBundle/Resources/config/routing/all.xml"
  prefix: /registration