root:
   path: /
   controller: App\Controller\DefaultController

user_register:
    path: /user/register
    controller: App\Controller\User\UserRegisterController
    
user_login:
    path: /user/login
    controller: App\Controller\User\UserLoginController

user_logout:
    path: /user/logout

team_list:
    path: /team/list
    controller: App\Controller\Team\TeamListController

team_create:
    path: /team/create
    controller: App\Controller\Team\TeamCreateController

team_show:
    path: /team/{team_id}
    controller: App\Controller\Team\TeamShowController

api_login:
    path: /api/login