parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\DataFixtures\Processor\:
        resource: '../src/DataFixtures/Processor'
        tags: ['fidry_alice_data_fixtures.processor']

    Payum\Core\Payum:
        alias: 'payum'

    App\Service\ResetPasswordTokenService:
        arguments:
            $sender: '%env(MAILGUN_SENDER)%'

    App\Controller\Team\TeamPaymentVerifyController:
        arguments:
            $sender: '%env(MAILGUN_SENDER)%'
        tags: ['controller.service_arguments']
