parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Factories are used by behat which needs them to be public so it can use them
    App\Behat\:
        resource: '../behat/src'
        autowire: true
        autoconfigure: true
        public: true

    # Also used by behat so that database can be "purged" before each test run
    Doctrine\Common\DataFixtures\Purger\ORMPurger:
        class: 'Doctrine\Common\DataFixtures\Purger\ORMPurger'
        autowire: true
        public: true

    GuzzleHttp\Client:
        class: 'GuzzleHttp\Client'

    GuzzleHttp\ClientInterface:
        alias: 'GuzzleHttp\Client'

    Faker\Generator:
        class: 'Faker\Generator'
        factory: ['Faker\Factory', 'create']