parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Factories are for behat which needs them to be public so it can use them
    App\Factory\:
        resource: '../src/Factory'
        public: true

    # Also used by behat so that database can be "purged" before each test run
    Doctrine\Common\DataFixtures\Purger\ORMPurger:
        class: 'Doctrine\Common\DataFixtures\Purger\ORMPurger'
        arguments: ['@Doctrine\ORM\EntityManagerInterface']
        public: true